%w{
  construct-success
  construct-success-2
  docjockey
  rboard
  construct-success-branch
}.


each do |project|
  GithubBuild.start(JSON.parse(File.read(File.join(RAILS_ROOT,"spec/fixtures/#{project}"))))
end

Tip.create([
 {"command"=>"twonklist", "description"=>"The twonklist", "id"=>1, "text"=>"http://twonklist.com - A place to name and shame the less desirable people of the world.", "user_id"=>nil},
 {"command"=>"finders", "description"=>"Link to finders guide", "id"=>2, "text"=>"http://guides.rubyonrails.org/active_record_querying.html - ActiveRecord Querying Guide by Ryan Bigg", "user_id"=>nil},
 {"command"=>"routing", "description"=>"Routing Guide", "id"=>3, "text"=>"http://guides.rubyonrails.org/routing.html - Rails Routing From the Outside In - Rails Guide - by Mike Gunderloy", "user_id"=>nil},
 {"command"=>"associations", "description"=>"Association Guide", "id"=>4, "text"=>"http://guides.rubyonrails.org/association_basics.html - Active Record Association Basics by Mike Gunderloy", "user_id"=>nil},
 {"command"=>"rails-view-lookup", "description"=>"How Rails selects which view to render", "id"=>5, "text"=>"http://stuff.lilleaas.net/how_rails_selects_which_view_to_render - Which conditions Rails uses in order to determine which view file to render when controller actions are invoked.", "user_id"=>nil},
 {"command"=>"routing-overview", "description"=>"", "id"=>6, "text"=>"http://frozenplague.net?p=108 - An introductory guide to RESTful Routing.", "user_id"=>nil},
 {"command"=>"guides", "description"=>"guides.rails.info", "id"=>7, "text"=>"http://guides.rubyonrails.org/ - Ruby on Rails guides, part of the ongoing hackfest", "user_id"=>nil},
 {"command"=>"pastie", "description"=>"Our Bitch", "id"=>8, "text"=>"http://pastie.org - Paste code examples there, and post the URL of the pastie here when you're done. http://pastie.org/help/ for more info on usage.", "user_id"=>nil},
 {"command"=>"botsnack", "description"=>"Give logga some love", "id"=>9, "text"=>"Nom nom. Thanks, {nick}!", "user_id"=>nil},
 {"command"=>"peepcode", "description"=>"Ya know.", "id"=>10, "text"=>"http://peepcode.com - Awesome screencasts of very high quality and relevance. The $9 is totally worth it.", "user_id"=>nil},
 {"command"=>"railscasts", "description"=>"", "id"=>11, "text"=>"http://railscasts.com - Great free screencasts by Ryan Bates. Tips, tricks and best practices.", "user_id"=>nil},
 {"command"=>"lighthouse", "description"=>"", "id"=>12, "text"=>"http://lighthouseapp.com -- beautiful simple issue tracking", "user_id"=>nil},
 {"command"=>"fatmodel", "description"=>"Skinny Controller, Fat Model", "id"=>13, "text"=>"http://weblog.jamisbuck.org/2006/10/18/skinny-controller-fat-model - Place the logic where it's supposed to be placed", "user_id"=>nil},
 {"command"=>"rails-lighthouse", "description"=>"", "id"=>14, "text"=>"http://rails.lighthouseapp.com - Rails issue tracking", "user_id"=>nil},
 {"command"=>"wwrd", "description"=>"wwrd", "id"=>15, "text"=>"What would Radar do?", "user_id"=>nil},
 {"command"=>"windows", "description"=>"FAQ entry for Windows", "id"=>16, "text"=>"http://frozenplague.net/?page_id=175#windows", "user_id"=>nil},
 {"command"=>"scaffold", "description"=>"", "id"=>17, "text"=>"http://tpope.us/rubyonrailsfaq.html", "user_id"=>nil},
 {"command"=>"passenger", "description"=>"Passenger overview / resources link", "id"=>18, "text"=>"Passenger (mod_rails) is an Apache / nginx module for running Rails applications. It is fast, sexy and very easy to setup. http://www.modrails.com/\n\nOther resources: Peepcode's setup guide: http://peepcode.com/products/phusion-passenger Railscasts: http://railscasts.com/episodes/122-passenger-in-development", "user_id"=>nil},
 {"command"=>"webhosts", "description"=>"A list of recommended webhosts", "id"=>19, "text"=>"Ruby on Rails hosting can be provided for by any (decent) webhost, for a list of webhosts (we won't normally recommend them) look here: http://wiki.rubyonrails.com/rails/pages/RailsWebHosts", "user_id"=>nil},
 {"command"=>"php", "description"=>"PHP + Narley Comment", "id"=>20, "text"=>"<Narley>: PHP is Russia and Ruby on Rails is America", "user_id"=>nil},
 {"command"=>"help", "description"=>"Dummy command", "id"=>21, "text"=>"", "user_id"=>nil},
 {"command"=>"google", "description"=>"DUD COMMAND", "id"=>22, "text"=>"", "user_id"=>nil},
 {"command"=>"rubyonrails-talk", "description"=>"Link to rubyonrails-talk", "id"=>23, "text"=>"http://groups.google.com/group/rubyonrails-talk", "user_id"=>nil},
 {"command"=>"yourownblog", "description"=>"The nubyonrails article on memcached that mentions writing your own blog", "id"=>24, "text"=>"http://nubyonrails.com/articles/about-this-blog-memcached - Every beginning Rails developer should write their own blog software.", "user_id"=>nil},
 {"command"=>"vampire", "description"=>"", "id"=>25, "text"=>"Help vampire detected by {nick}. Dispersing e-Garlic and wooden stakes.", "user_id"=>nil},
 {"command"=>"select_all", "description"=>"Link to select all section of finders guide", "id"=>26, "text"=>"http://guides.rails.info/finders.html#_tt_select_all_tt", "user_id"=>nil},
 {"command"=>"i18n", "description"=>"Guide on i18n for Rails 2.2", "id"=>27, "text"=>"http://guides.rubyonrails.org/i18n.html - Guide on i18n by Sven Fuchs and Karel Mina\xC5\x99\xC3\xADk", "user_id"=>nil},
 {"command"=>"howtoaskforhelp", "description"=>"", "id"=>28, "text"=>"http://frozenplague.net/?p=267", "user_id"=>nil},
 {"command"=>"acl", "description"=>"acl_system", "id"=>29, "text"=>"http://github.com/ezmobius/acl_system2", "user_id"=>nil},
 {"command"=>"skitch", "description"=>"Image sharing program for Mac OS X", "id"=>30, "text"=>"http://skitch.com - Image sharing site with related application for Mac OS X", "user_id"=>nil},
 {"command"=>"deploy-ubuntu", "description"=>"", "id"=>31, "text"=>"Deploying on Ubuntu / Debian using Apache, Rails, Passenger and Capistrano: http://frozenplague.net/?p=230", "user_id"=>nil},
 {"command"=>"quickref", "description"=>"Ryan Davis' Ruby quckref", "id"=>32, "text"=>"http://www.zenspider.com/Languages/Ruby/QuickRef.html - Quick reference for the Ruby Language", "user_id"=>nil},
 {"command"=>"multi-updates", "description"=>"", "id"=>33, "text"=>"http://github.com/Radar/multi-updates/tree/master - An example application of how to update multiple rows from the same model at the same time.", "user_id"=>nil},
 {"command"=>"editor", "description"=>"A list of IDE and Editors for Rails", "id"=>34, "text"=>"Commonly used Rails editors: Textmate, Vim, Aptana, Emacs, Netbeans, Eclipse and (NOT) Dreamweaver (see !ide for ide lists)", "user_id"=>nil},
 {"command"=>"ide", "description"=>"A list of IDE's for Rails", "id"=>35, "text"=>"Eclipse, Netbeans and Aptana. Please note if you are on Mac Os X an IDE is not recommended.", "user_id"=>nil},
 {"command"=>"git", "description"=>"Git decription", "id"=>36, "text"=>"Git is a version control system used for both Ruby on Rails and most plugin / gems. See http://git.or.cz/ for Git, http://github.com/ or http://unfuddle.com for hosting and http://railscasts.com/episodes/96 for managing Rails applications with git", "user_id"=>nil},
 {"command"=>"beginner", "description"=>"A list of beginner resources for RoR", "id"=>37, "text"=>"Resources for beginning in Ruby on Rails: http://guides.rubyonrails.org/ - http://peepcode.com/ - http://railscasts.com/", "user_id"=>nil},
 {"command"=>"cms", "description"=>"Content Management Systems for RoR", "id"=>38, "text"=>"Content Managmenet Systems for Ruby on Rails: Typo http://typosphere.org - Mephisto http://mephistoblog.com/ - RadiantCMS http://radiantcms.org/", "user_id"=>nil},
 {"command"=>"haml", "description"=>"Haml resources", "id"=>39, "text"=>"Haml is an alternative markup to HTML, for help and information please see the documentation http://haml.hamptoncatlin.com/docs/ or ##haml", "user_id"=>nil},
 {"command"=>"docs", "description"=>"Documetation listings for Rails and Ruby", "id"=>40, "text"=>"Rails: http://api.rubyonrails.org/ Ruby: http://www.ruby-doc.org/core/", "user_id"=>nil},
 {"command"=>"hosts", "description"=>"Ruby on Rails host details", "id"=>41, "text"=>"Ruby on Rails hosting can be provided for by any (decent) webhost, for a list of webhosts (we won't normally recommend them) look here: http://wiki.rubyonrails.com/rails/pages/RailsWebHosts", "user_id"=>nil},
 {"command"=>"ask", "description"=>"Don't ask to ask, just ask!", "id"=>43, "text"=>"Don't ask to ask, just ask! http://www.catb.org/~esr/faqs/smart-questions.html", "user_id"=>nil},
 {"command"=>"capistrano", "description"=>"Capistrano link <b>(needs more!)</b>", "id"=>44, "text"=>"Capistrano is a neat deployment method for Rails applications, see the capistrano site for more details http://www.capify.org/getting-started/rails", "user_id"=>nil},
 {"command"=>"contributing", "description"=>"", "id"=>45, "text"=>"How to contribute to Rails, written by Mike Gunderloy: http://afreshcup.com/2008/10/27/contributing-to-rails-step-by-step/", "user_id"=>nil},
 {"command"=>"wwod", "description"=>"What would obama do?", "id"=>46, "text"=>"What would Obama do?", "user_id"=>nil},
 {"command"=>"ajax", "description"=>"Ajax help", "id"=>47, "text"=>"New to Ajax / Javascript? Before asking a million questions in the channel please have a look through some great resources: http://peepcode.com/products/javascript-with-prototypejs http://peepcode.com/products/ajax-with-prototypejs", "user_id"=>nil},
 {"command"=>"demons", "description"=>"No john", "id"=>48, "text"=>"No John you are the demons", "user_id"=>nil},
 {"command"=>"association-basics", "description"=>"Association Basics Guide", "id"=>49, "text"=>"http://guides.rubyonrails.org/association_basics.html by Mike Gunderloy", "user_id"=>nil},
 {"command"=>"notabug", "description"=>"It's probably not a bug", "id"=>50, "text"=>"It's probably not a bug: http://www.catb.org/esr/faqs/smart-questions.html#id306810", "user_id"=>nil},
 {"command"=>"pebkac", "description"=>"", "id"=>51, "text"=>"PEBKAC: Problem Existing Between Keyboard And Chair. Also known as \"User Error\"", "user_id"=>1},
 {"command"=>"used", "description"=>"", "id"=>52, "text"=>"Don't ask \"has anybody used <thing>?\". It's better to just ask your problem and if anyone has used <thing> they will most likely answer.", "user_id"=>1},
 {"command"=>"best", "description"=>"", "id"=>53, "text"=>"\"Best\" and \"better\" are subjective. Try to use a different term.", "user_id"=>1},
 {"command"=>"cte", "description"=>"", "id"=>54, "text"=>"You must remove the line from config/environments/development.rb and config/environments/production.rb in order to get your app to function correctly: http://frozenplague.net/2008/11/cache-template-extensions-error/", "user_id"=>1},
 {"command"=>"textmate", "description"=>"kick-ass editor for Macs", "id"=>55, "text"=>"Kick-ass text editor for Macs.  If you have a Mac, code, and don't use TextMate you're a fool.  http://macromates.com/", "user_id"=>7},
 {"command"=>"zen", "description"=>"find your peace", "id"=>56, "text"=>"Relax, take a deep breath, find your center - peace is waiting for you there.", "user_id"=>7},
 {"command"=>"rails-ubuntu", "description"=>"", "id"=>57, "text"=>"How to set up and deploy on Ubuntu: http://frozenplague.net/2008/09/ubuntu-rails-apache-passenger-capistrano-you/", "user_id"=>1},
 {"command"=>"scale", "description"=>"rails doesn't scale", "id"=>58, "text"=>"Ruby on Rails doesn't scale - nothing to see here - move along.  http://twitter.com/", "user_id"=>7},
 {"command"=>"try", "description"=>"", "id"=>59, "text"=>"Why don't you try it and find out for yourself?", "user_id"=>1},
 {"command"=>"pickaxe", "description"=>"Programming Ruby", "id"=>60, "text"=>"http://rubycentral.com/book - Programming Ruby is a free online book on Ruby.", "user_id"=>8},
 {"command"=>"everused", "description"=>"", "id"=>61, "text"=>"just post the fucking bug already", "user_id"=>9},
 {"command"=>"rtft", "description"=>"Read the fucking topic", "id"=>62, "text"=>"This channel has a topic that contains helpful links. One of these links may help you. If you cannot see the topic, type /topic and press enter.", "user_id"=>1},
 {"command"=>"version", "description"=>"", "id"=>63, "text"=>"Please tell us what version of Ruby, Rubygems and Rails you're running on so we can better help you. Also if you haven't already tell us your operating system too.", "user_id"=>1},
 {"command"=>"logs", "description"=>"", "id"=>64, "text"=>"Check your logs. Namely everything in the log folder of your rails app and the error and access logs from Apache or whatever else you're using.", "user_id"=>1},
 {"command"=>"language", "description"=>"", "id"=>65, "text"=>"wash your mouth out!", "user_id"=>9},
 {"command"=>"expert", "description"=>"", "id"=>66, "text"=>"we all like to think we're experts; just ask your question", "user_id"=>9},
 {"command"=>"section", "description"=>"", "id"=>67, "text"=>"Please section your pasties using the syntax of \"## section header\", for more information see this: http://skitch.com/radarlistener/9d6i/new-pastie", "user_id"=>1},
 {"command"=>"paperclip", "description"=>"", "id"=>68, "text"=>"http://www.thoughtbot.com/projects/paperclip/ - A file upload plugin for Rails. w/ example http://github.com/anathematic/paperclip_example/tree/master", "user_id"=>1},
 {"command"=>"attachment_fu", "description"=>"", "id"=>69, "text"=>"http://github.com/technoweenie/attachment_fu/tree/master - A file upload plugin for Rails.", "user_id"=>1},
 {"command"=>"rboard", "description"=>"", "id"=>70, "text"=>"http://github.com/radar/rboard - A forum system built in Rails. It's compatible with Rails 2.2 and includes internationalization support.", "user_id"=>1},
 {"command"=>"fucktard", "description"=>"", "id"=>71, "text"=>"Dear sir, I am not of high opinion of your intelligence.", "user_id"=>1},
 {"command"=>"camel", "description"=>"Id rather mate with a camel than...", "id"=>72, "text"=>"I would rather mate with a camel than listen to you bitching, go google your issue and stop being a gibbon!", "user_id"=>11},
 {"command"=>"cock", "description"=>"you must be compensating ", "id"=>73, "text"=>"you must be compensating for having a very small penis, otherwise it escapes my why you would be such a giant cock in public!", "user_id"=>11},
 {"command"=>"flame", "description"=>"my texteditor is bigger than yours", "id"=>74, "text"=>"look my texteditor is better than yours STFU", "user_id"=>11},
 {"command"=>"monkeyattack", "description"=>"we are winding up the clockwork monkeys", "id"=>75, "text"=>"we are winding up the clockwork monkeys, they will be round to collect your liver shortly...", "user_id"=>11},
 {"command"=>"trout", "description"=>"Im a pacifist but...", "id"=>76, "text"=>"Im terribly sorry about this! I am a pacifist but I must do my masters bidding so would you mind awfully holding still whilst I insert this trout up your nostril?", "user_id"=>11},
 {"command"=>"tutorial", "description"=>"you can probably find a tutorial on it on either..", "id"=>77, "text"=>"you can probably find a tutorial on it on either, http://www.railscasts.com or http://www.peepcode.com", "user_id"=>11},
 {"command"=>"migrations", "description"=>"", "id"=>78, "text"=>"http://guides.rubyonrails.org/migrations.html - Migrations Guide by Frederick Cheung ", "user_id"=>1},
 {"command"=>"gettingstarted", "description"=>"", "id"=>79, "text"=>"http://guides.rubyonrails.org/getting_started.html - Getting started with Ruby on Rails guide written by Mike Gunderloy", "user_id"=>1},
 {"command"=>"restful-routing", "description"=>"", "id"=>80, "text"=>"http://frozenplague.net/2008/01/restful-routing-an-overview/ - Shorter guide to RESTful routing with Rails.", "user_id"=>1},
 {"command"=>"will_paginate", "description"=>"", "id"=>81, "text"=>"http://github.com/mislav/will_paginate/tree/master - Pagination plugin for Rails.", "user_id"=>1},
 {"command"=>"howlong", "description"=>"", "id"=>82, "text"=>"http://www.google.com.au/search?q=how+long+is+a+piece+of+string", "user_id"=>1},
 {"command"=>"ohgoditburns", "description"=>"", "id"=>83, "text"=>"Your HTML skills are inferior: http://catb.org/esr/html-hell.html", "user_id"=>1},
 {"command"=>"jquery", "description"=>"The jQuery JavaScript Library", "id"=>84, "text"=>"Main site: http://jquery.com/\nDocs: http://visualjquery.com/", "user_id"=>16},
 {"command"=>"rubygems", "description"=>"", "id"=>85, "text"=>"http://rubyforge.org/frs/?group_id=126 - The latest version of Rubygems (and all other versions) can be found here. Download the archived version, extract it and run \"ruby setup.rb\" to install it.", "user_id"=>16},
 {"command"=>"rspec", "description"=>"", "id"=>86, "text"=>"http://rspec.info - RSpec is a Behaviour Driven Development framework for Ruby. ", "user_id"=>1},
 {"command"=>"cucumber", "description"=>"", "id"=>87, "text"=>"Cucumber - Successor to stories for rspec http://github.com/aslakhellesoy/cucumber/tree/master", "user_id"=>1},
 {"command"=>"texteditor", "description"=>"", "id"=>88, "text"=>"Windows - \"E Text Editor\" - http://www.e-texteditor.com/\nLinux - Vim (http://www.vim.org/) or Emacs (http://www.gnu.org/software/emacs/)\nMac - TextMate (http://macromates.com/) or Vim, Emacs (as above)", "user_id"=>1},
 {"command"=>"arrayconditions", "description"=>"", "id"=>89, "text"=>"How to use array conditions in find statements ([\"field = ?\", some_variable]) http://guides.rubyonrails.org/finders.html#_array_conditions", "user_id"=>1},
 {"command"=>"rest", "description"=>"", "id"=>90, "text"=>"REST - (REpresentational State Transfer) - http://en.wikipedia.org/wiki/Representational_State_Transfer", "user_id"=>1},
 {"command"=>"thinkingsphinx", "description"=>"", "id"=>91, "text"=>"http://ts.freelancing-gods.com/ - Thinking Sphinx - Plugin for Rails, uses Sphinx (full-text search engine for MySQL and PostgreSQL)", "user_id"=>1},
 {"command"=>"wrong", "description"=>"You're wrong", "id"=>92, "text"=>"http://www.youtube.com/watch?v=WrjwaqZfjIY", "user_id"=>8},
 {"command"=>"dry", "description"=>"Don't Repeat Yourself", "id"=>93, "text"=>"Don't repeat yourself. Asking the same question repeatedly will not give you more answers.", "user_id"=>8},
 {"command"=>"books", "description"=>"Link to list of Ruby and Rails books", "id"=>94, "text"=>"What book should you get? - http://is.gd/hYWq", "user_id"=>8},
 {"command"=>"gist", "description"=>"", "id"=>95, "text"=>"http://gist.github.com - Put your codes online with pretty syntax highlighting and the ability to embed it into other pages.", "user_id"=>1},
 {"command"=>"slicehost", "description"=>"", "id"=>96, "text"=>"http://slicehost.com - A hosting company that provides a box that you can install Ruby on Rails on to.", "user_id"=>1},
 {"command"=>"ruby191", "description"=>"", "id"=>97, "text"=>"Ruby 1.9.1 does NOT work with certain Rubygems and may not be fully compatible with Rails yet. For more information see : http://frozenplague.net/2009/01/ruby-191-rubygems-rails/ and http://isitruby19.com\r\n ", "user_id"=>1},
 {"command"=>"activemerchant", "description"=>"", "id"=>98, "text"=>"Activemerchant provides you with a way to interact between your application and supported payment gateways: http://github.com/Shopify/active_merchant/tree/master", "user_id"=>1},
 {"command"=>"saasy", "description"=>"", "id"=>99, "text"=>"SaaSy: Scaffold-like application for payment gateways (uses ActiveMerchant): http://github.com/maccman/saasy/tree/master", "user_id"=>1},
 {"command"=>"auth", "description"=>"", "id"=>100, "text"=>"If you want to implement user's with passwords in your application, you can use AuthLogic: http://github.com/binarylogic/authlogic/tree/master or Restful Authentication: http://github.com/technoweenie/restful-authentication/tree/master", "user_id"=>1},
 {"command"=>"survivalguide", "description"=>"", "id"=>101, "text"=>"http://tore.darell.no/doc.html - Survival guide for Ruby. Must read.", "user_id"=>1},
 {"command"=>"wiki", "description"=>"", "id"=>102, "text"=>"http://wiki.rubyonrails.org/", "user_id"=>7},
 {"command"=>"errors", "description"=>"", "id"=>103, "text"=>"To have no errors\n  would be life without meaning.\n    No struggle, no joy.", "user_id"=>9},
 {"command"=>"ducktyping", "description"=>"", "id"=>104, "text"=>"Learn about Duck Typing here: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/100511", "user_id"=>1},
 {"command"=>"tags", "description"=>nil, "id"=>105, "text"=>"tag plugins : http://github.com/mbleigh/acts-as-taggable-on/tree/master w/ plugin example: http://github.com/anathematic/taggable-example/tree/master", "user_id"=>nil},
 {"command"=>"application", "description"=>nil, "id"=>106, "text"=>"As of Rails 2.3 ApplicationController has been moved from app/controllers/application.rb to app/controllers/application_controller.rb to better follow convention. Rename your application.rb file using 'rake rails:update:application_controller'.", "user_id"=>nil},
 {"command"=>"render", "description"=>nil, "id"=>107, "text"=>"Layouts and Rendering Guide by Mike Gunderloy", "user_id"=>nil},
 {"command"=>"layout", "description"=>nil, "id"=>108, "text"=>"Layouts and Rendering Guide by Mike Gunderloy", "user_id"=>nil},
 {"command"=>"cache_template_loading", "description"=>nil, "id"=>109, "text"=>"cache_template_loading= is a deprecated method. Remove this from all files in config/environments", "user_id"=>nil},
 {"command"=>"tasks", "description"=>nil, "id"=>110, "text"=>"Have you checked the rake tasks for your project, yet?  Simply type 'rake -T' inside your application's directory to list the available rake tasks.\n", "user_id"=>nil},
 {"command"=>"expectedgot", "description"=>nil, "id"=>111, "text"=>"If you're getting Model(#[num]) expected, got String(#[num]) this is because you're passing in from the form a parameter with the name of a belongs_to association. Make sure you change the field name to association_id.", "user_id"=>nil},
 {"command"=>"elaborate", "description"=>nil, "id"=>112, "text"=>"Instead of simply saying 'something is broken' please elaborate on this by showing us the code and the error that you are getting by making a pastie (http://pastie.org) about it.", "user_id"=>nil},
 {"command"=>"files", "description"=>nil, "id"=>113, "text"=>"Storing files in the database will only lead to misery and heartbreak. Store files where they belong, in the filesystem. Use a file-upload plugin such as Paperclip to acheive this.", "user_id"=>nil},
 {"command"=>"caching", "description"=>nil, "id"=>114, "text"=>"Caching with Rails Guide - http://guides.rubyonrails.org/caching_with_rails.html - by Aditya Chadha", "user_id"=>nil},
 {"command"=>"topic", "description"=>nil, "id"=>115, "text"=>"Read the topic. It contains useful information. Failure to read the topic will result in horrible consequences.", "user_id"=>nil},
 {"command"=>"validations", "description"=>nil, "id"=>116, "text"=>"How to make your own custom validations: http://august.lilleaas.net/creating_your_own_validations", "user_id"=>nil},
 {"command"=>"command_line", "description"=>nil, "id"=>117, "text"=>"Command Line Guide written by Colin Curtin", "user_id"=>nil},
 {"command"=>"locales", "description"=>nil, "id"=>118, "text"=>"A comprehensive list of locales and exxamples of translation Rails' default messages - http://github.com/svenfuchs/rails-i18n/tree/d19c80c14b1c3da06822a0cde6ed0ce048f5971f/rails/locale", "user_id"=>nil},
 {"command"=>"mindread", "description"=>nil, "id"=>119, "text"=>"Sorry, we are unable to read your mind at this time. Please pastie (http://pastie.org) your code and any relevant stacktrace so we can assist you.", "user_id"=>nil},
 {"command"=>"subjective", "description"=>nil, "id"=>120, "text"=>"What you just asked could be classed as subjective. Subjective questions often start flamewars, which are tedious and boring. Try all the available options and see which one suits you the best.", "user_id"=>nil},
 {"command"=>"doubleroutes", "description"=>nil, "id"=>121, "text"=>"It looks like you have the same resource defined twice. Try removing one of them and seeing if that fixes your problem.", "user_id"=>nil},
 {"command"=>"ydiw", "description"=>nil, "id"=>122, "text"=>"Be open to the idea that you're doing it wrong.", "user_id"=>nil},
 {"command"=>"bion", "description"=>nil, "id"=>123, "text"=>"Believe it or not, we're actually here to help you be a better programmer.", "user_id"=>nil},
 {"command"=>"fans", "description"=>nil, "id"=>124, "text"=>"Looking to create a has_and_belongs_to_many relationship through the same table?  (e.g. friends or followers?) look no further than http://github.com/radar/fans", "user_id"=>nil},
 {"command"=>"pastebinsucks", "description"=>nil, "id"=>125, "text"=>"Pastebin sucks! Use http://pastie.org or http://gist.github.com please!", "user_id"=>nil},
 {"command"=>"pbcompare", "description"=>nil, "id"=>126, "text"=>"Pastebin: http://skitch.com/ryanbigg/nnxxn/pastebin vs Pastie: http://skitch.com/ryanbigg/nnxxf/pastie. I know which I'd prefer", "user_id"=>nil},
 {"command"=>"explain", "description"=>nil, "id"=>127, "text"=>"Please explain your problem better as we are having trouble understanding what you mean. A pastie (http://pastie.org) is always helpful!", "user_id"=>nil},
 {"command"=>"exceptional", "description"=>nil, "id"=>128, "text"=>"http://getexceptional.com/ - Get Exceptional - Exception logging for your Rails application", "user_id"=>nil},
 {"command"=>"hoptoad", "description"=>nil, "id"=>129, "text"=>"http://www.hoptoadapp.com/ - Hoptoad - Exception logging for your Rails application", "user_id"=>nil},
 {"command"=>"newrelic", "description"=>nil, "id"=>130, "text"=>"http://www.newrelic.com/ - New Relic - Reports for your Rails application", "user_id"=>nil},
 {"command"=>"acl9", "description"=>nil, "id"=>131, "text"=>"http://github.com/be9/acl9 - Access Control List for controlling what users have access to what resources", "user_id"=>nil}])